### PR TITLE
Translate to Japanese

### PR DESCRIPTION
**Pull request by k-ta-yamada**
Hello, @rumoroso.

I have always been helped by this extension "HeadingsMap" that you have created.
I have translated it into Japanese to help you a little.
I would be happy if you could help me when you have time.

I think there might be something wrong with the `message.json`, as I didn't understand how each `message` is used in some parts of it. In that case, I would be happy to correct it again.

* Please forgive me if the text is strange because this is a machine translation.

### CODE REVIEW

**Comment by rumoroso** [comment]
Hi @k-ta-yamada , first of all, thank you very much for this translation. I really appreciate it. It makes be very happy to see that the extension is useful and that people are willing to collaborate this way.

About how the file message.json is used, I can understand it can be a bit confusing. Basically I made it this way and it grew up organically, and maybe, I should think about how to improve it. If there is something that was not clear, do not hesitate and let me know.

I will take a look on how the translations work when integrated in the extension. All that I can do is to check that everything works and that it goes fine, because of course I don't know any word in Japanesse :D  I'll let you know how it goes.

Let me know also if you need something in which I could help.

Btw, since adding this translation will generate a new release, I will update the release notes mentioning it. Could you please translate this sentence: "Added the translation to Japanesse provided by 'k-ta-yamada'. Thank you very much for this collaboration and the effort. I really appreciate it."   I used your user name from here, from Github, but if you prefer to change it and use other name or so, feel to do it. You can add this translation here, as a comment, and I can add it later to the file. ;)

**Comment by k-ta-yamada** [comment]
The `html/help/en.html` was deleted by mistake.
We have recovered and rebased it.

**Comment by k-ta-yamada** [comment]
https://github.com/rumoroso/headingsmap_translations/pull/10/commits/83bda33c8896661bfbbd7ff10998ceb3ae7a0b7b

We have corrected what we believe to be duplicate sentences.
If this is a mistake, please let us know and we will remove the commit.

**Comment by k-ta-yamada** [comment]
Thank you for your reply.

> I will take a look on how the translations work when integrated in the extension.
> All that I can do is to check that everything works and that it goes fine, because of course I don't know any word in Japanesse :D I'll let you know how it goes.

Yes, I will check again when it is released.
I think it will probably be ok, but I may send you another revision of the translation at that time.

> Could you please translate this sentence:
> "Added the translation to Japanesse provided by 'k-ta-yamada'. Thank you very much for this collaboration and the effort.  I really appreciate it."

Thanks for the addition. The translation looks like this:

```
k-ta-yamada による日本語訳を追加しました。
この協力と努力に感謝します。本当に感謝しています。
```

I have one suggestion for HTML documentation.
Would it be possible to have one sentence correspond to one line as follows?

```html
<li><strong>Translations</strong>: So far, the extension is available in four languages (English, French,
    Spanish and Polish), and it would be great if more languages are added. Do you speak Italian, German,
    Japanese, ...? Do not hesitate and contribute to the internationalization of the extension. I've created
    a GitHub repository with the translatable texts. The URL is
    <a href="https://github.com/rumoroso/headingsmap_translations/tree/main">
        https://github.com/rumoroso/headingsmap_translations/tree/main
    </a>. If you have any doubt or any question, you can send an email to the address that I created for the
    extension: <a href="mailto:headingsmap@gmail.com?subject=Translation for headingsMap extension">
        headingsmap@gmail.com
    </a>.
</li>
```
↓
```html
<li>
    <strong>Translations</strong>:
    So far, the extension is available in four languages (English, French, Spanish and Polish), and it would be great if more languages are added. Do you speak Italian, German, Japanese, ...?
    Do not hesitate and contribute to the internationalization of the extension.
    I've created a GitHub repository with the translatable texts.
    The URL is <a href="https://github.com/rumoroso/headingsmap_translations/tree/main">https://github.com/rumoroso/headingsmap_translations/tree/main</a>.
    If you have any doubt or any question, you can send an email to the address that I created for the extension:
    <a href="mailto:headingsmap@gmail.com?subject=Translation for headingsMap extension">headingsmap@gmail.com</a>.
</li>

```

This may make it easier to check and correct differences when translating in the future.
However, it may be difficult to do so for various reasons, such as the effect of formatters, or if the HTML is output mechanically or automatically to begin with.
In such cases, please feel free to dismiss this proposal.

**Comment by rumoroso** [comment]
Hi, thank you again for being that fast doing changes, reviewing it, etc., for contributing and giving your very useful feedback.
> 
> I have one suggestion for HTML documentation. Would it be possible to have one sentence correspond to one line as follows?
> 
> ```
> <li>
>     <strong>Translations</strong>:
>     So far, the extension is available in four languages (English, French, Spanish and Polish), and it would be great if more languages are added. Do you speak Italian, German, Japanese, ...?
>     Do not hesitate and contribute to the internationalization of the extension.
>     I've created a GitHub repository with the translatable texts.
>     The URL is <a href="https://github.com/rumoroso/headingsmap_translations/tree/main">https://github.com/rumoroso/headingsmap_translations/tree/main</a>.
>     If you have any doubt or any question, you can send an email to the address that I created for the extension:
>     <a href="mailto:headingsmap@gmail.com?subject=Translation for headingsMap extension">headingsmap@gmail.com</a>.
> </li>
> ```
> 
> This may make it easier to check and correct differences when translating in the future. However, it may be difficult to do so for various reasons, such as the effect of formatters, or if the HTML is output mechanically or automatically to begin with. In such cases, please feel free to dismiss this proposal.

I think this is a very good feedback, and also a good proposal. So far, the way in which these files are organized, formatted, etc., only respond to how they were created and how the extension grew up, but nothing else. This means that most likely, the developer experience is not the best, and I think your idea is a good way to improve it. I will start taking a look to those details. Thank you very much for sharing your idea, I think it is good. I appreciate all improvements oriented to have a better user experience, a better developer experience, a...   better extension for all.

If you don't mind, I would like to ask you for a small change in that part of the translation. It says:
```So far, the extension is available in four languages (English, French, Spanish and Polish), and it would be great if more languages are added. Do you speak Italian, German, Japanese, ...?```, but with this PR, there will be 5 translations, so maybe the sentence should be: ```So far, the extension is available in five languages (English, French, Spanish, Polish, and Japanesse), and it would be great if more languages are added. Do you speak Italian, German, ...? ```. Maybe you already did it, but I just wanted to be sure :)

**Comment by k-ta-yamada** [comment]
Thank you.
I am glad you accept my suggestions for improvement.

> If you don't mind, I would like to ask you for a small change in that part of the translation. 

Oops, I missed it.
I modified `html/contribute/en.html` and also modified `html/contribute/en.html`.
We have also modified `html/contribute/en.html` as per the earlier improvement proposal,
If you prefer not to modify it yet because you are still considering it, please feel free to let us know.

The fixes are committed as a `fixup`.
After you check it, it would be great if you could `git rebase` it to the first commit.

**Comment by rumoroso** [comment]
I think everything looks good to me, so I'll merge the changes. After the merge, the changes will be also pushed to the extension. I will do a small improvement in the extension and release the new version, hopefully on Monday or Tuesday. The version for Firefox is usually released very fast in the Mozilla store, and it usually takes longer for Chrome and Edge. Anyway I will write a new comment here to let you know when it is done. I already said it a few times, but I'll repeat it again... thank you very much for everything. 

Best wishes,
Jorge

**Comment by rumoroso** [comment]
Hi, it's me again. I just wanted to tell you that the new version of the extension was already released for Firefox and Chrome (I guess for Edge it will take a bit longer). Thank you for all

**Comment by k-ta-yamada** [comment]
Thank you for the release!
I have checked the new version released on Chrome and Firefox as well.
The translation of `message.json`, which I was concerned about, seems to be OK.
Thank you very much for taking the translation in.

---

This is not related to translation, but the following message appears in Paypal after pressing the donate button, and it seems that the donation cannot be made.

"この受取人への寄付は、この国ではサポートされていません"
↓(English translation)
"Donations to this recipient are not supported in this country".

Are there any relevant settings in your Paypal account settings, etc.?
If not, is it possible to make a donation as described in the following link "Sending Money via PayPal"?
https://www.openbsdfoundation.org/donations.html

**Comment by rumoroso** [comment]
Hi @k-ta-yamada , thank you very much (again :) ) for confirming that it seems to be OK.

Regarding the Paypal behavior, I didn't know that could happen :/ I will review the settings to check whether something can be changed. I didn't know that other option for sending money via Paypal that you referenced in that link. I never used it, but now that I know this could happen, maybe I'll update the contribution section to include it. I think the only thing needed is the mail. I will write something similar to what that page says: 

> _"If you are unable to use the donation button, but still wish to contribute, you can do it in Paypal by using the address: rumoroso@gmail.com"_ 
 
Could I ask you to make a final favor of translating that sentence? You wouldn't need to create a PR, but just add it as comment here, because I am working in an update (these latest weeks a did a bunch of them), so I can add it directly. And of course, it is not urgent, so no rush :)

**Comment by k-ta-yamada** [comment]
Hi @rumoroso.
The translation of the sentence to be added is as follows.

```
寄付ボタンを使用できない場合でも寄付をご希望頂ける場合、Paypal で次のアドレスを使用して寄付を行うことができます: rumoroso@gmail.com
```

> because I am working in an update (these latest weeks a did a bunch of them)

I'm looking forward to seeing more of this.
I continue to support your passion for this extension.
I would be honored to assist you in any way again.

**Comment by rumoroso** [comment]
Thank you very much. I cannot stop repeating how I really appreciate all that you did. :)

**Pull request merged**
