### PR TITLE
polish

### PR DESCRIPTION
**Pull request by Wloclawek**

### CODE REVIEW

**Comment by Wloclawek** [comment]
Polish language added

**Comment by rumoroso** [comment]
Hi @Wloclawek , thank you very much for the translation. I really appreciate it. There is a couple of things that I would like to ask if possible:

- I just realized that I forgot to update the file for the release notes, so I just did it. It is just a couple of lines that were added. Could you please take that change and translate it?
- Since I will release the extension with the translation in a new version, I will have to add another line in the release notes to mention it. That content is not yet there and I'll add it as soon I add the translations to the package. Because of that, I would like to ask you if it is OK for you if I write something like:  _Translated to Polish by Wloclawek (the name here can be what you prefer). Thank you very much your voluntary collaboration. It is really appreciated._  ?  And if it is OK, could you please translate it?

Again, thank you very much for this. I really appreciate it. :)

**Comment by Wloclawek** [comment]
Hi,

Your project is great and has helped many times. Thank you. I translated the added text. You can sign: Translated to Polish by Rafał Jendrzejewski.

Greetings :)

**Comment by rumoroso** [comment]
Thank you very much again for this. I really appreciate it.

**Pull request merged**
